#pragma once
#include <iostream>
#include "objects\horizontal_line.h"
#include "objects\print.h"
#include "objects\println.h"
#include "objects\square.h"
#include "objects\triangle.h"
#include "objects\mnl.h"
#include "objects\color.h"
#include "objects\vert_line.h"